import Head from "next/head";
import { useState } from "react";

import { FaLaptopCode } from "react-icons/fa";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";
import ihsaan from "../public/ihsaan-clothing-home-page.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const downloadPDF = () => {
    fetch("Resume 2022.pdf").then((response) => {
      response.blob().then((blob) => {
        const fileURL = window.URL.createObjectURL(blob);
        let alink = document.createElement("a");
        alink.href = fileURL;
        alink.download = "Resume 2022.pdf";
        alink.click();
      });
    });
  };

  return (
    <div>
      <Head>
        <title>Abu Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <nav className="py-10 mb-12 flex justify-between">
          <FaLaptopCode
            className="w-10 h-6 "
            onClick={() => setDarkMode(!darkMode)}
          />
          <ul className="flex items-center">
            <li>
              <a
                className="bg-gradient-to-r from-black to-gray-600 text-white px-4 py-2 rounded-md ml-8 cursor-pointer"
                onClick={downloadPDF}
              >
                Resume
              </a>
            </li>
          </ul>
        </nav>
        <section className="drop-shadow-lg shadow-lg p-10 max-w-full">
          <div className="text-center">
            <h2 className="text-5xl text-teal-600 font-medium">Abu </h2>
            <h3 className="text-2xl py-2">Software Engineer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Software Engineer with expertise in RPA and Full Stack Web
              Development. My journey started in 2018 when I transitioned from
              being a Corporate Accountant to an RPA Developer at Prologis.
              Since then, I have been able to earn a M.S. in Information Systems
              from the University Of Colorado Denver in 2020 and have become
              well versed in RPA and Web Development
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16">
            <a href="https://github.com/abu-jeylani">
              <AiFillGithub />
            </a>
            <a href="https://www.linkedin.com/in/abu-m-5884a676/IMG_7967">
              <AiFillLinkedin />
            </a>
          </div>
        </section>
        <section className="py-2">
          <div className="lg:flex gap-10">
            <div className="text-center drop-shadow-lg shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <a href="https://ihsaan-clothing.netlify.app/">
                <Image
                  alt="ihsaan app"
                  src={ihsaan}
                  width={400}
                  height={100}
                  className="mx-auto cursor-pointer"
                />
              </a>
              <a href="https://ihsaan-clothing.netlify.app/">
                <h3 className="text-lg font-medium pt-8 pb-2 cursor-pointer">
                  Ihsaan Clothing
                </h3>
              </a>

              <p className="py-2">
                An e-commerce website I developed for customers to buy fashion
                products
              </p>
              <h4 className="py-4 text-teal-600">Tech Used:</h4>
              <p className="text-gray-800 py-1">React (Front-End)</p>
              <p className="text-gray-800 py-1">Firebase (Back-End)</p>
              <p className="text-gray-800 py-1">Github (Repo)</p>
              <p className="text-gray-800 py-1">Netlify (Hosting Service)</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
